#include "logos_img.h"

extern const uint8_t logo_frames_map[];

#define LOGO_FRAME_BYTES (56 * 56 * 3)

const lv_img_dsc_t logo_img[LOGO_COUNT] = {
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 0,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 1,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 2,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 3,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 4,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 5,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 6,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 7,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 8,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 9,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 10,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 11,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 12,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 13,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 14,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 15,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 16,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 17,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 18,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 19,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 20,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 21,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 22,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 23,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 24,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 25,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 26,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 27,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 28,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 29,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 30,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 31,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 32,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 33,
    },
    {
        .header.always_zero = 0,
        .header.w = 56,
        .header.h = 56,
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data_size = LOGO_FRAME_BYTES,
        .data = logo_frames_map + LOGO_FRAME_BYTES * 34,
    },
};
