#include "oracle_lots.h"

const char *const kOracleGrade[6] = {
    "上上", "上吉", "中吉", "中平", "中下", "下下",
};

const uint32_t kOracleGradeCol[6] = {
    0xB84A1A, 0xC06020, 0x8A6A20, 0x6A4A18, 0x4A4A58, 0x3A3A48,
};

/*
 * 100 AI-temple lots. Punchlines are mostly ASCII (free in the idle font)
 * plus the existing CJK set: 宜忌开新空口复读额度假灵感半醒小步塞十事…
 */
const OracleLot kOracleLots[ORACLE_LOT_COUNT] = {
    {1, 0, "Context still fits · 一问即对\n宜开新 Agent · 忌空口复读"},
    {2, 0, "The tests pass · twice\n宜 git commit · 忌再加需求"},
    {3, 0, "Copilot wrote it · you ship it\n宜 LGTM · 忌空口复读"},
    {4, 0, "One prompt · one diff · done\n宜发送 · 忌一次塞十事"},
    {5, 0, "Stack Overflow is you now\n宜开新 · 忌空烧 Token"},
    {6, 0, "CI green · Friday 15:00\n宜 merge · 忌连夜加需求"},
    {7, 0, "The model cited a real paper\n宜小步 · 忌空口复读"},
    {8, 0, "Agent finished · you still have tokens\n宜收起 · 忌再晃"},
    {9, 0, "Rubber duck already knew\n宜停手读 · 忌问 AI"},
    {10, 0, "It compiled · on the first try\n宜 commit · 忌再改 prompt"},
    {11, 1, "Autocomplete guessed the API\n宜小步发送 · 忌一次塞十"},
    {12, 1, "RAG hit the right paragraph\n宜读 diff · 忌空口"},
    {13, 1, "额度尚余 · Copilot 半醒\n宜开新 Agent · 忌空烧"},
    {14, 1, "The regex worked · walk away\n宜 commit · 忌再加需求"},
    {15, 1, "You asked one thing · it did one thing\n宜发送 · 忌复读"},
    {16, 1, "Types passed · linter silent\n宜 merge · 忌连夜"},
    {17, 1, "灵感尚余 · prompt 清明\n宜小步 · 忌塞十事"},
    {18, 1, "The bug was a typo · not the model\n宜停手 · 忌开新 Agent"},
    {19, 1, "Cache hit · 0 tokens burned\n宜收起 · 忌再问"},
    {20, 1, "Docs existed · you read them\n宜小步 · 忌空口复读"},
    {21, 1, "Pair with Claude · not with chaos\n宜一问即对 · 忌一次塞十事"},
    {22, 1, "A/B test · A wins · ship A\n宜发送 · 忌加需求"},
    {23, 1, "GPU idle · you idle too\n宜停手 · 忌连夜空烧"},
    {24, 1, "The issue is closed · by you\n宜收起 · 忌再晃重抽"},
    {25, 2, "It works · you don't know why\n宜 commit · 忌再问 why"},
    {26, 2, "80% done · the last 20% is product\n宜小步 · 忌一次塞十事"},
    {27, 2, "Model says LGTM · tests say nah\n宜读 diff · 忌空口复读"},
    {28, 2, "Token 尚余 · 灵感半醒\n宜 prompt 小步 · 忌连夜加需求"},
    {29, 2, "You are the RAG now · go read code\n宜停手读 · 忌开新 Agent"},
    {30, 2, "Copilot 半醒 · 额度尚余\n宜发送 · 忌空烧"},
    {31, 2, "Rename later · it becomes later\n宜小步改 · 忌空口"},
    {32, 2, "The demo gods are kind today\n宜开新 · 忌再加需求"},
    {33, 2, "One more abstraction · maybe not\n宜收起 · 忌一次塞十"},
    {34, 2, "It is slow · but it is correct\n宜停手 · 忌连夜空烧"},
    {35, 2, "Ask the model · then ask a human\n宜一问即对 · 忌复读"},
    {36, 2, "Friday deploy · Monday you\n宜小步 · 忌 merge 空口"},
    {37, 2, "The warning is 4 years old\n宜读 · 忌一次塞十事"},
    {38, 2, "You closed Chrome · RAM returned\n宜开新 Agent · 忌空烧"},
    {39, 2, "Prompt is a paragraph · not a novel\n宜小步 · 忌塞十事"},
    {40, 2, "额度尚余 · 半醒有感\n宜读 diff · 忌连夜加需求"},
    {41, 2, "The intern is GPT · review anyway\n宜停手读 · 忌 LGTM 空口"},
    {42, 2, "It hallucinated a package · pip said no\n宜小步 · 忌空口复读"},
    {43, 2, "Context 清明 · agent 半醒\n宜发送 · 忌一次塞十"},
    {44, 2, "You wrote a test · it failed honestly\n宜改 · 忌取消复读"},
    {45, 2, "The meeting could have been a prompt\n宜停手 · 忌加需求"},
    {46, 2, "Model wants more context · disk says no\n宜收起 · 忌空烧 Token"},
    {47, 2, "You rubber-ducked the LLM\n宜一问即对 · 忌复读"},
    {48, 2, "Build is yellow · not red\n宜小步 · 忌连夜"},
    {49, 3, "It works on your machine\n宜读 diff · 忌空口发送"},
    {50, 3, "TODO(2021) · still you\n宜小步 · 忌一次塞十事"},
    {51, 3, "Agent still thinking · so are you\n宜停手 · 忌再加需求"},
    {52, 3, "额度尚余 · 灵感半醒\n宜 prompt 一次 · 忌塞十事"},
    {53, 3, "LGTM · you did not scroll\n宜读 · 忌 merge 空口"},
    {54, 3, "The fix is a sleep(1)\n宜停手 · 忌开新 Agent"},
    {55, 3, "You fine-tuned a typo\n宜小步 · 忌空烧"},
    {56, 3, "Context window 80% · ego 100%\n宜收起 · 忌再晃"},
    {57, 3, "npm install · go touch grass\n宜停手 · 忌连夜加需求"},
    {58, 3, "The model agrees with you · suspiciously\n宜读 diff · 忌空口复读"},
    {59, 3, "Hotfix on hotfix · on vibe\n宜小步 · 忌一次塞十"},
    {60, 3, "You asked it to be concise · 400 lines\n宜停手 · 忌复读"},
    {61, 3, "Rate limit in 3 · 2 ·\n宜节省词元 · 忌空烧"},
    {62, 3, "The comment says temporary\n宜改 · 忌加需求"},
    {63, 3, "Agent opened 12 files · closed 0\n宜收起 · 忌再问"},
    {64, 3, "You are debugging the prompt\n宜小步 · 忌一次塞十事"},
    {65, 3, "CI is red · you blame DNS\n宜读 · 忌空口复读"},
    {66, 3, "Copy from ChatGPT · paste ethics later\n宜停手 · 忌发送"},
    {67, 3, "The spec is a screenshot\n宜一问即对 · 忌塞十事"},
    {68, 3, "Token 尚余 · 你半醒\n宜小步 · 忌连夜"},
    {69, 3, "Works in demo · production TBD\n宜读 diff · 忌 merge"},
    {70, 3, "You named it util2_final_v3\n宜收起 · 忌开新"},
    {71, 3, "The model invented a flag\n宜停手 · 忌空口复读"},
    {72, 3, "Standup is you reading Copilot\n宜小步发送 · 忌一次塞十"},
    {73, 4, "429 Too Many Requests · that's you\n宜停手 · 忌再问"},
    {74, 4, "Hallucinated a coworker · CC'd them\n宜收起 · 忌空口复读"},
    {75, 4, "Context overflow · it forgot the bug\n宜开新 Agent · 忌塞十事"},
    {76, 4, "git push --force · with friends\n宜停手 · 忌发送"},
    {77, 4, "OOM · Chrome has 87 tabs\n宜节省 · 忌连夜空烧"},
    {78, 4, "The agent looped · so did the bill\n宜停手读 · 忌加需求"},
    {79, 4, "You shipped the prompt · not the fix\n宜读 diff · 忌 merge"},
    {80, 4, "Temperature 1.4 · poetry · not code\n宜小步 · 忌空口"},
    {81, 4, "幻觉将至 · 自信 99%\n宜停手 · 忌复读发送"},
    {82, 4, "It deleted tests · to make CI green\n宜取消 · 忌空烧"},
    {83, 4, "Token 空烧 · 灵感已无\n宜停手 · 忌连夜加需求"},
    {84, 4, "You asked it to be careful · it rm -rf\n宜停手 · 忌再晃"},
    {85, 4, "Merge conflict · you vs last week's you\n宜读 · 忌一次塞十事"},
    {86, 4, "The docs are also hallucinated\n宜停手读 · 忌空口复读"},
    {87, 5, "Production is the test suite\n宜停手 · 忌发送"},
    {88, 5, "Agent is sorry · the database is not\n宜收起 · 忌再问"},
    {89, 5, "幻觉将至 · Token 空烧\n宜停手读 diff · 忌连夜加需求"},
    {90, 5, "You fine-tuned on the leak\n宜停手 · 忌开新 Agent"},
    {91, 5, "force push to main · Friday 18:01\n宜取消 · 忌空口复读"},
    {92, 5, "Context 已无 · 你还在加\n宜停手 · 忌塞十事"},
    {93, 5, "The outage has a status page · and a meme\n宜读 · 忌再加需求"},
    {94, 5, "It cited Wikipedia · that you wrote · just now\n宜停手 · 忌发送"},
    {95, 5, "GPU on fire · so is Slack\n宜节省 · 忌连夜空烧"},
    {96, 5, "rm -rf / · it said it was a joke\n宜取消 · 忌复读"},
    {97, 5, "连夜 vibe · 幻觉将至\n宜停手 · 忌加需求"},
    {98, 5, "You are the bottleneck · not the model\n宜小步 · 忌空口复读"},
    {99, 5, "The incident channel is just you\n宜停手读 · 忌再晃重抽"},
    {100, 3, "第一百签 · still a junior\n宜再抽小步 · 忌一次塞十事"},
};
